// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using testni_zadatak.EfCore;

#nullable disable

namespace testni_zadatak.Migrations
{
    [DbContext(typeof(EF_DataContext))]
    [Migration("20230525130339_UpdateReference9")]
    partial class UpdateReference9
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GmlCoordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GmlFeatureId")
                        .HasColumnType("integer");

                    b.Property<int?>("GmlFeatureId1")
                        .HasColumnType("integer");

                    b.Property<double[]>("X")
                        .HasColumnType("double precision[]");

                    b.Property<double[]>("Y")
                        .HasColumnType("double precision[]");

                    b.HasKey("Id");

                    b.HasIndex("GmlFeatureId")
                        .IsUnique();

                    b.HasIndex("GmlFeatureId1")
                        .IsUnique();

                    b.ToTable("GmlCoordinates");
                });

            modelBuilder.Entity("GmlFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FeatureType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GmlFeatures");
                });

            modelBuilder.Entity("GmlCoordinate", b =>
                {
                    b.HasOne("GmlFeature", "GmlFeature")
                        .WithOne("Coordinates")
                        .HasForeignKey("GmlCoordinate", "GmlFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GmlFeature", null)
                        .WithOne("values")
                        .HasForeignKey("GmlCoordinate", "GmlFeatureId1");

                    b.Navigation("GmlFeature");
                });

            modelBuilder.Entity("GmlFeature", b =>
                {
                    b.Navigation("Coordinates");

                    b.Navigation("values");
                });
#pragma warning restore 612, 618
        }
    }
}
